version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WEATHER_API_KEY=5926157dbbb51a83853152b24cb0c6ab
      - DJANGO_SETTINGS_MODULE=weatherproject.settings
    volumes:
      - sqlite_data:/app
    restart: unless-stopped

volumes:
  sqlite_data:
