apiVersion: apps/v1
kind: Deployment
metadata:
  name: skypulse-deployment
  labels:
    app: skypulse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skypulse
  template:
    metadata:
      labels:
        app: skypulse
    spec:
      containers:
        - name: skypulse
          image: skypulse:latest
          imagePullPolicy: Never       # use local Minikube image
          ports:
            - containerPort: 8000
          env:
            - name: WEATHER_API_KEY
              value: "5926157dbbb51a83853152b24cb0c6ab"
            - name: DJANGO_SETTINGS_MODULE
              value: "weatherproject.settings"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
