apiVersion: v1
kind: Service
metadata:
  name: skypulse-service
  labels:
    app: skypulse
spec:
  type: NodePort
  selector:
    app: skypulse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
